document.addEventListener('DOMContentLoaded', () => {
  'use strict';

  const form = document.getElementById('quoteRequestForm');

  if (!form) {
    console.error('[Fleet Parlour] quoteRequestForm not found.');
    return;
  }

  const button = form.querySelector('button[type="submit"]');
  const status = document.getElementById('quoteFormStatus');
  const photoInput = document.getElementById('job_photos');

  function showStatus(message, type = 'info') {
    if (!status) return;

    status.textContent = message;
    status.classList.remove(
      'text-muted',
      'text-success',
      'text-danger',
      'text-warning'
    );

    if (type === 'success') {
      status.classList.add('text-success');
    } else if (type === 'error') {
      status.classList.add('text-danger');
    } else if (type === 'warning') {
      status.classList.add('text-warning');
    } else {
      status.classList.add('text-muted');
    }
  }

  form.addEventListener('submit', async (event) => {
    event.preventDefault();
    event.stopPropagation();

    if (!form.checkValidity()) {
      form.reportValidity();
      return;
    }

    if (photoInput) {
      const files = Array.from(photoInput.files || []);

      if (files.length < 1) {
        showStatus('Please attach at least one job photo.', 'error');
        return;
      }

      if (files.length > 10) {
        showStatus('Please upload no more than 10 photos.', 'error');
        return;
      }

      const maxSize = 8 * 1024 * 1024;

      const tooLarge = files.find((file) => file.size > maxSize);

      if (tooLarge) {
        showStatus(
          `${tooLarge.name} is larger than 8 MB. Please choose a smaller photo.`,
          'error'
        );
        return;
      }
    }

    const originalButtonText = button
      ? button.textContent
      : 'Request My Free Quote';

    try {
      if (button) {
        button.disabled = true;
        button.textContent = 'Submitting...';
      }

      showStatus('Submitting your quote request...', 'info');

      const apiBase = String(
        window.FLEET_PARLOUR_API_URL || window.location.origin
      ).replace(/\/+$/, '');

      const response = await fetch(`${apiBase}/api/enquiries`, {
        method: 'POST',
        body: new FormData(form)
      });

      let result;

      try {
        result = await response.json();
      } catch (error) {
        throw new Error('The server returned an invalid response.');
      }

      if (!response.ok || result.ok !== true) {
        throw new Error(
          result?.error ||
          result?.message ||
          'Unable to submit your enquiry.'
        );
      }

      // Use exactly the same reference generated by server.js
      let referenceCode = result.reference_code;

      if (!referenceCode && result.enquiry_id) {
        const compactId = String(result.enquiry_id)
          .replace(/-/g, '')
          .slice(0, 8)
          .toUpperCase();

        referenceCode = `FP-${compactId}`;
      }

      if (!referenceCode) {
        referenceCode = 'FP-RECEIVED';
      }

      // Redirect immediately to Thank You page
      const thankYouUrl =
        `${window.location.origin}/thank-you.html` +
        `?ref=${encodeURIComponent(referenceCode)}` +
        `&notified=${result.email_notification === true ? '1' : '0'}`;

      console.log('[Fleet Parlour] Redirecting to:', thankYouUrl);

      window.location.assign(thankYouUrl);

      return;

    } catch (error) {
      console.error('[Fleet Parlour] Form error:', error);

      showStatus(
        error.message ||
        'Unable to submit your request. Please try again.',
        'error'
      );

      if (button) {
        button.disabled = false;
        button.textContent = originalButtonText;
      }
    }
  });
});